language: python
sudo: required
matrix:
  include:
    - os: linux
      python: 2.7
      env: SOUND=jack
    - os: linux
      python: 3.6
      env: SOUND=jack
    - os: osx
      language: generic
      env: PY=2 SOUND=coreaudio
    - os: osx
      language: generic
      env: PY=3 SOUND=coreaudio
addons:
  apt:
    packages:
      - libjack-jackd2-dev
      - libportmidi-dev
      - portaudio19-dev
      - liblo-dev
      - libsndfile-dev
  artifacts:
    paths:
      - $(ls ./*.whl | tr "\n" ":")
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install liblo libsndfile portaudio portmidi
      if [[ "$PY" == "3" ]]; then
        brew install python3
        virtualenv venv -p python3
      else
        virtualenv venv
      fi
      source venv/bin/activate
    fi
script:
  - pip wheel . --build-option="--use-${SOUND}" --build-option="--use-double"
